routes/web.php
<?php

use App\Http\Middleware\Activated;
use App\Http\Middleware\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware(['auth', Activated::class])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::namespace('Admin')->group(function () {
            Route::middleware(Admin::class)->group(function () {
            });
            
            Route::get('/', 'HomeController@index')->name('admin');
            Route::get('profile', 'UserController@profile')->name('profile');
    
            Route::post('bill-products', 'BillProductController@store')->name('bill-products.store');
            Route::post('receipt-products', 'ReceiptProductController@store')->name('receipt-products.store');
            Route::post('products/read', 'ProductController@products')->name('products.read');
    
            Route::put('bill-products', 'BillProductController@update')->name('bill-products.update');
            Route::put('receipt-products', 'ReceiptProductController@update')->name('receipt-products.update');
    
            Route::delete('bill-products', 'BillProductController@destroy')->name('bill-products.destroy');
            Route::delete('receipt-products', 'ReceiptProductController@destroy')->name('receipt-products.destroy');
    
            Route::resource('bills', 'BillController');
            Route::resource('customers', 'CustomerController')->except(['show']);
            Route::resource('cities', 'CityController')->except(['show']);
            Route::resource('categories', 'CategoryController')->except(['show']);
            Route::resource('contents', 'ContentController');
            Route::resource('menus', 'MenuController');
            Route::resource('languages', 'LanguageController')->except(['show']);
            Route::resource('districts', 'DistrictController')->except(['show']);
            Route::resource('employees', 'EmployeeController')->except(['show']);
            Route::resource('products', 'ProductController')->except(['show']);
            Route::resource('providers', 'ProviderController')->except(['show']);
            Route::resource('receipts', 'ReceiptController');
            // Route::resource('receipt-products', 'ReceiptProductController');
            Route::resource('types', 'TypeController')->except(['show']);
            Route::resource('users', 'UserController')->except(['show']);
            Route::resource('wards', 'WardController')->except(['show']);
            Route::post('city-district', 'WardController@city_district')->name('wards.city_district');
            Route::post('district-ward', 'WardController@district_ward')->name('wards.district_ward');
    
        });
    });
});

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('{menu}', 'HomeController@menu')->where('menu', '([A-Za-z0-9\-\/]+)');
});

resources/views/admin/receipts/create.blade.php
@extends('layouts.admin')

@section('title', 'INNOSOFT')

@section('content')
<form method="POST" action="{{ route('receipts.store') }}" role="form">
@method('POST')
@csrf
    <nav class="navbar navbar-light bg-white shadow">
        <div class="navbar-brand">{{ __('admin/receipts.detail') }}</div>
        <div class="mr-auto">
            <a class="btn btn-outline-dark my-0" href="{{ url()->previous() == url()->current() ? route('receipts.index') : url()->previous() }}">{{ __('admin/table.back') }}</a>
        </div>
        <button type="submit" class="btn btn-success" onclick="$('#continue').val(0)">{{ __('admin/table.save') }}</button>
        <input type="text" class="form-control" id="continue" name="continue" value="{{ old('continue', 1) }}" hidden>
        <button type="submit" class="btn btn-primary ml-2" onclick="$('#continue').val(1)">{{ __('admin/table.save-continue') }}</button>
    </nav>

    <div class="bg-white my-3 p-3 shadow">
        <h3>{{ __('admin\receipts.receipt_info') }}</h3>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="symbole">{{ __('admin/receipts.symbole') }}</label>
                    <input type="text" class="form-control" name="symbole" id="symbole" placeholder="{{ __('admin/receipts.symbole') }}" maxlength="191" value="{{ old('symbole') }}">
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="form-group">
                    <label for="receipt_number">{{ __('admin/receipts.receipt_number') }} (*)</label>
                    <input type="text" class="form-control" name="receipt_number" id="receipt_number" placeholder="{{ __('admin/receipts.receipt_number') }}" maxlength="191" value="{{ old('receipt_number')}}" required>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label for="receipt_date_pick">{{ __('admin/receipts.receipt_date') }}</label>
                    <input type="text" class="form-control" id="receipt_date_pick" placeholder="{{ __('admin/receipts.receipt_date') }}">
                    <input type="text" class="form-control" id="receipt_date" name="receipt_date" value="{{ old('receipt_date', now()) }}" hidden>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white my-3 p-3 shadow">
        <h3>{{ __('admin\receipts.provider_info') }}</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="provider_id">{{ __('admin/receipts.provider_id') }} (*)</label>
                    <select name="provider_id" class="form-control" id="provider_id">
                        <option value="" disabled selected> Chọn nhà cung cấp</option>
                        @foreach ($providers as $provider)
                            <option value="{{ $provider->id }}" data-provider-phone="{{ $provider->phone }}" data-provider-address = "{{ $provider->address }}" data-provider-taxid = "{{ $provider->tax_id }}">{{ $provider->provider_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label for="provider_name">{{ __('admin/receipts.provider_name') }} (*)</label>
                    <input type="text" class="form-control" name="provider_name" id="provider_name" placeholder="{{ __('admin/receipts.provider_name') }}" maxlength="191" value="{{ old('provider_name') }}" required>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label for="tax_id">{{ __('admin/receipts.tax_id')  }}</label>
                    <input type="text" class="form-control" name="tax_id" id="tax_id" placeholder="{{ __('admin/receipts.tax_id') }}" maxlength="191" value="{{ old('tax_id') }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="address">{{ __('admin/receipts.address') }}</label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="{{ __('admin/receipts.address') }}" maxlength="191" value="{{ old('address') }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">{{ __('admin/receipts.phone') }}</label>
                    <input type="text" class="form-control" name="phone" id="phone" placeholder="{{ __('admin/receipts.phone') }}" maxlength="191" value="{{ old('phone') }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="fax">{{ __('admin/receipts.fax') }}</label>
                    <input type="text" class="form-control" name="fax" id="fax" placeholder="{{ __('admin/receipts.fax') }}" maxlength="191" value="{{ old('fax') }}">
                </div>
            </div>
        
            <div class="col-md-12">
                <div class="form-group">
                    <label for="note">{{ __('admin/receipts.note') }}</label>
                    <textarea class="form-control" name="note" id="note" rows="3" placeholder="{{ __('admin/receipts.note') }}" value="{{ old('note')}}" ></textarea>
                </div>
            </div>
        </div>
    </div>
    <!-- Content -->
</form>
@endsection

@push('js')
    <script>
        $(function() {
            $("#receipt_date_pick").daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                minYear: 1901,
                maxYear: parseInt(moment().format("YYYY"),10),
                locale: {
                    format: "DD/MM/YYYY"
                }
            }, function(start, end, label) {
                $('#receipt_date').val(start.format("YYYY-MM-DD"));
            });
        });
        $("#provider_id").on("change", function(){
             var selected_provider = $(this).children("option:selected");
            $("#address").val(selected_provider.attr("data-provider-address"));
            $("#tax_id").val(selected_provider.attr("data-provider-taxid"));
            $("#phone").val(selected_provider.attr("data-provider-phone"));
            $("#provider_name").val(selected_provider.text());
        })
    </script>
@endpush

@push('ready')
    @if (count($errors) > 0)
    toastr["error"]("@foreach ($errors->all() as $error) <li>{{ $error }}</li> @endforeach");
    @endif
    $("#provider_id").val("{{ old('provider_id') }}");
@endpush

resources/views/admin/receipts/edit.blade.php
@extends('layouts.admin')

@section('title', 'INNOSOFT')

@section('content')
<form method="POST" action="{{ route($route . '.update', ['id' => $data->id]) }}" role="form">
@method('PUT')
@csrf
    <nav class="navbar navbar-light bg-white shadow">
        <div class="navbar-brand">{{ __('admin/users.detail') }}</div>
        <div class="mr-auto">
            <a class="btn btn-outline-dark my-0" href="{{ url()->previous() == url()->current() ? route($route . '.index') : url()->previous() }}">{{ __('admin/table.back') }}</a>
        </div>
        <button type="submit" class="btn btn-success" onclick="$('#continue').val(0)">{{ __('admin/table.save') }}</button>
        <input type="text" class="form-control" id="continue" name="continue" value="{{ old('continue', 1) }}" hidden>
        <button type="submit" class="btn btn-primary ml-2" onclick="$('#continue').val(1)">{{ __('admin/table.save-continue') }}</button>
    </nav>
    <div class="bg-white my-3 p-3 shadow">
        <h3>{{ __('admin\receipts.receipt_info') }}</h3>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="symbole">{{ __('admin/receipts.symbole') }}</label>
                    <input type="text" class="form-control" name="symbole" id="symbole" placeholder="{{ __('admin/receipts.symbole') }}" maxlength="191" value="{{ old('symbole', $data->symbole) }}">
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="form-group">
                    <label for="receipt_number">{{ __('admin/receipts.receipt_number') }} (*)</label>
                    <input type="text" class="form-control" name="receipt_number" id="receipt_number" placeholder="{{ __('admin/receipts.receipt_number') }}" maxlength="191" value="{{ old('receipt_number', $data->receipt_number)}}" min="0" required>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label for="receipt_date_pick">{{ __('admin/receipts.receipt_date') }}</label>
                    <input type="text" class="form-control" id="receipt_date_pick" placeholder="{{ __('admin/receipts.receipt_date') }}">
                    <input type="text" class="form-control" id="receipt_date" name="receipt_date" value="{{ old('receipt_date', $data->receipt_date) }}" hidden>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white my-3 p-3 shadow">
        <h3>{{ __('admin\receipts.provider_info') }}</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="provider_id">{{ __('admin/receipts.provider_id') }} (*)</label>
                    <select name="provider_id" class="form-control" id="provider_id">
                        <option value="" disabled selected> Chọn nhà cung cấp</option>
                        @foreach ($providers as $provider)
                            <option value="{{ $provider->id }}" data-provider-phone="{{ $provider->phone }}" data-provider-address = "{{ $provider->address }}" data-provider-taxid = "{{ $provider->tax_id }}">{{ $provider->provider_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label for="provider_name">{{ __('admin/receipts.provider_name') }} (*)</label>
                    <input type="text" class="form-control" name="provider_name" id="provider_name" placeholder="{{ __('admin/receipts.provider_name') }}" maxlength="191" value="{{ old('provider_name', $data->provider_name) }}" required>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label for="tax_id">{{ __('admin/receipts.tax_id')  }}</label>
                    <input type="text" class="form-control" name="tax_id" id="tax_id" placeholder="{{ __('admin/receipts.tax_id') }}" maxlength="191" value="{{ old('tax_id', $data->tax_id) }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="address">{{ __('admin/receipts.address') }}</label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="{{ __('admin/receipts.address') }}" maxlength="191" value="{{ old('address', $data->address) }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">{{ __('admin/receipts.phone') }}</label>
                    <input type="text" class="form-control" name="phone" id="phone" placeholder="{{ __('admin/receipts.phone') }}" maxlength="191" value="{{ old('phone', $data->phone) }}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="fax">{{ __('admin/receipts.fax') }}</label>
                    <input type="text" class="form-control" name="fax" id="fax" placeholder="{{ __('admin/receipts.fax') }}" maxlength="191" value="{{ old('fax', $data->fax) }}">
                </div>
            </div>
        
            <div class="col-md-12">
                <div class="form-group">
                    <label for="note">{{ __('admin/receipts.note') }}</label>
                    <textarea class="form-control" name="note" id="note" rows="3" placeholder="{{ __('admin/receipts.note') }}" value="{{ old('note', $data->note)}}" ></textarea>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@push('js')
    <script>
        $(function() {
            $("#receipt_date_pick").daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                startDate: moment("{{ $data->receipt_date }}"),
                minYear: 1901,
                maxYear: parseInt(moment().format("YYYY"),10),
                locale: {
                    format: "DD/MM/YYYY"
                }
            }, function(start, end, label) {
                $('#receipt_date').val(start.format("YYYY-MM-DD"));
            });
        });

        $("#provider_id").on("change", function () {
             var selected_provider = $(this).children("option:selected");
            $("#address").val(selected_provider.attr("data-provider-address"));
            $("#tax_id").val(selected_provider.attr("data-provider-taxid"));
            $("#phone").val(selected_provider.attr("data-provider-phone"));
            $("#provider_name").val(selected_provider.text());
        })
    </script>
@endpush

@push('ready')
    @if (count($errors) > 0)
    toastr["error"]("@foreach ($errors->all() as $error) <li>{{ $error }}</li> @endforeach");
    @endif
    $("#provider_id").val("{{ old('provider_id', $data->provider_id) }}");
@endpush

resources/views/admin/receipts/index.blade.php
@extends('layouts.admin')

@section('title', 'INNOSOFT')

@section('content')
<nav class="navbar navbar-light bg-white shadow">
    <div class="navbar-brand">{{ __('admin/receipts.lists') }}</div>
    <div class="mr-auto">
        @if (Route::has("$route.create"))
        <a class="btn btn-success" href="{{ route($route . '.create') }}">
            {{ __('admin/table.create') }}
        </a>
        @endif
    </div>
</nav>
<div class="bg-white div-content my-3 p-3 table-responsive shadow">
    <table id="table-data" class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{{ __('admin/receipts.user_id') }}</th>
                <th scope="col">{{ __('admin/receipts.receipt_number') }}</th>
                <th scope="col">{{ __('admin/receipts.receipt_date') }}</th>
                <th scope="col">{{ __('admin/receipts.provider_id') }}</th>
                <th scope="col">{{ __('admin/receipts.provider_name') }}</th>
                <th scope="col">{{ __('admin/receipts.tax_id') }}</th>
                <th scope="col">{{ __('admin/receipts.symbole') }}</th>
                <th scope="col">{{ __('admin/receipts.vat') }}</th>
                <th scope="col">{{ __('admin/receipts.total') }}</th>
                @if (Route::has($route . '.show'))
                <th scope="col" style="width: 3rem;"></th>
                @endif
                @if (Route::has($route . '.edit'))
                <th scope="col" style="width: 3rem;"></th>
                @endif
                @if (Route::has($route . '.destroy'))
                <th scope="col" style="width: 3rem;"></th>
                @endif
            </tr>
        </thead>
        <tbody id="data">
            @if ($data_table->total() == 0)
            <tr>
                <td colspan="15"><center>{{ __('admin/table.no_data') }}</center></td>
            </tr>
            @endif
            @foreach ($data_table as $index => $data)
            <tr>
                <th scope="row">{{ $data->id }}</th>
                <td>{{ $data->user_id }}</td>
                <td>{{ $data->receipt_number }}</td>
                <td>{{ date('d/m/Y', strtotime($data->receipt_date)) }}</td>
                <td>{{ $data->provider_id }}</td>
                <td>{{ $data->provider_name }}</td>
                <td>{{ $data->tax_id }}</td>
                <td>{{ $data->symbole }}</td>
                <td>{{ $data->vat }}</td>
                <td>{{ $data->total }}</td>
                @if (Route::has($route . '.show'))
                <td class="px-1">
                    <a href="{{ route($route . '.show', ['id' => $data->id]) }}" class="btn btn-warning" title="{{ __('admin/table.update') }}">
                        <i class="fas fa-eye" aria-hidden="true"></i>
                    </a>
                </td>
                @endif
                @if (Route::has($route . '.edit'))
                <td class="px-1">
                    <a href="{{ route($route . '.edit', ['id' => $data->id]) }}" class="btn btn-primary" title="{{ __('admin/table.update') }}">
                        <i class="fas fa-edit" aria-hidden="true"></i>
                    </a>
                </td>
                @endif
                @if (Route::has($route . '.destroy'))
                <td class="px-1">
                    <div data-toggle="modal" data-target="#cfmDel" onclick="$('#formDelete').attr('action', '{{ route($route . '.destroy', ['id' => $data->id]) }}');" class="btn btn-danger" title="{{ __('admin/table.delete') }}">
                        <i class="fas fa-trash" aria-hidden="true"></i>
                    </div>
                </td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="d-flex justify-content-between">
        {{ $data_table->links() }}
    </div>
</div>
<!--cfmDel-->
<div class="modal" id="cfmDel" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="cfmDel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form method="POST" action="" role="form" id="formDelete">
                    @method('DELETE')
                    @csrf
                    <h3>{{ __('admin/table.question_delete') }}</h3><br>
                    <button type="submit" class="btn btn-danger">{{ __('admin/table.delete') }}</button>
                    <button class="btn btn-default" data-dismiss="modal">{{ __('admin/table.cancel') }}</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('ready')
@if (session('success'))
toastr["success"]("{{ __('message.' . session('success')) }}");
@endif
@if (session('error'))
toastr["error"]("{{ __('message.' . session('error')) }}");
@endif
@endpush